/// A country with its ISO 3166-1 alpha-2 code and international calling code.
class Country {
  const Country(this.code, this.name, this.dialCode);

  final String code;
  final String name;

  /// Without the leading `+`.
  final String dialCode;

  /// The flag emoji, built from the code's regional indicator symbols.
  String get flag => String.fromCharCodes(
    code.toUpperCase().codeUnits.map((c) => 0x1F1E6 + c - 0x41),
  );

  static Country? byCode(String? code) {
    if (code == null) return null;
    final upper = code.toUpperCase();
    for (final country in all) {
      if (country.code == upper) return country;
    }
    return null;
  }

  /// Launch markets, shown first in pickers.
  static const featuredCodes = ['KE', 'IN', 'US'];

  static const all = <Country>[
    Country('AF', 'Afghanistan', '93'),
    Country('AL', 'Albania', '355'),
    Country('DZ', 'Algeria', '213'),
    Country('AD', 'Andorra', '376'),
    Country('AO', 'Angola', '244'),
    Country('AG', 'Antigua and Barbuda', '1'),
    Country('AR', 'Argentina', '54'),
    Country('AM', 'Armenia', '374'),
    Country('AU', 'Australia', '61'),
    Country('AT', 'Austria', '43'),
    Country('AZ', 'Azerbaijan', '994'),
    Country('BS', 'Bahamas', '1'),
    Country('BH', 'Bahrain', '973'),
    Country('BD', 'Bangladesh', '880'),
    Country('BB', 'Barbados', '1'),
    Country('BY', 'Belarus', '375'),
    Country('BE', 'Belgium', '32'),
    Country('BZ', 'Belize', '501'),
    Country('BJ', 'Benin', '229'),
    Country('BT', 'Bhutan', '975'),
    Country('BO', 'Bolivia', '591'),
    Country('BA', 'Bosnia and Herzegovina', '387'),
    Country('BW', 'Botswana', '267'),
    Country('BR', 'Brazil', '55'),
    Country('BN', 'Brunei', '673'),
    Country('BG', 'Bulgaria', '359'),
    Country('BF', 'Burkina Faso', '226'),
    Country('BI', 'Burundi', '257'),
    Country('CV', 'Cabo Verde', '238'),
    Country('KH', 'Cambodia', '855'),
    Country('CM', 'Cameroon', '237'),
    Country('CA', 'Canada', '1'),
    Country('CF', 'Central African Republic', '236'),
    Country('TD', 'Chad', '235'),
    Country('CL', 'Chile', '56'),
    Country('CN', 'China', '86'),
    Country('CO', 'Colombia', '57'),
    Country('KM', 'Comoros', '269'),
    Country('CG', 'Congo', '242'),
    Country('CD', 'Congo (DRC)', '243'),
    Country('CR', 'Costa Rica', '506'),
    Country('CI', "Côte d'Ivoire", '225'),
    Country('HR', 'Croatia', '385'),
    Country('CU', 'Cuba', '53'),
    Country('CY', 'Cyprus', '357'),
    Country('CZ', 'Czechia', '420'),
    Country('DK', 'Denmark', '45'),
    Country('DJ', 'Djibouti', '253'),
    Country('DM', 'Dominica', '1'),
    Country('DO', 'Dominican Republic', '1'),
    Country('EC', 'Ecuador', '593'),
    Country('EG', 'Egypt', '20'),
    Country('SV', 'El Salvador', '503'),
    Country('GQ', 'Equatorial Guinea', '240'),
    Country('ER', 'Eritrea', '291'),
    Country('EE', 'Estonia', '372'),
    Country('SZ', 'Eswatini', '268'),
    Country('ET', 'Ethiopia', '251'),
    Country('FJ', 'Fiji', '679'),
    Country('FI', 'Finland', '358'),
    Country('FR', 'France', '33'),
    Country('GA', 'Gabon', '241'),
    Country('GM', 'Gambia', '220'),
    Country('GE', 'Georgia', '995'),
    Country('DE', 'Germany', '49'),
    Country('GH', 'Ghana', '233'),
    Country('GR', 'Greece', '30'),
    Country('GD', 'Grenada', '1'),
    Country('GT', 'Guatemala', '502'),
    Country('GN', 'Guinea', '224'),
    Country('GW', 'Guinea-Bissau', '245'),
    Country('GY', 'Guyana', '592'),
    Country('HT', 'Haiti', '509'),
    Country('HN', 'Honduras', '504'),
    Country('HK', 'Hong Kong', '852'),
    Country('HU', 'Hungary', '36'),
    Country('IS', 'Iceland', '354'),
    Country('IN', 'India', '91'),
    Country('ID', 'Indonesia', '62'),
    Country('IR', 'Iran', '98'),
    Country('IQ', 'Iraq', '964'),
    Country('IE', 'Ireland', '353'),
    Country('IL', 'Israel', '972'),
    Country('IT', 'Italy', '39'),
    Country('JM', 'Jamaica', '1'),
    Country('JP', 'Japan', '81'),
    Country('JO', 'Jordan', '962'),
    Country('KZ', 'Kazakhstan', '7'),
    Country('KE', 'Kenya', '254'),
    Country('KI', 'Kiribati', '686'),
    Country('XK', 'Kosovo', '383'),
    Country('KW', 'Kuwait', '965'),
    Country('KG', 'Kyrgyzstan', '996'),
    Country('LA', 'Laos', '856'),
    Country('LV', 'Latvia', '371'),
    Country('LB', 'Lebanon', '961'),
    Country('LS', 'Lesotho', '266'),
    Country('LR', 'Liberia', '231'),
    Country('LY', 'Libya', '218'),
    Country('LI', 'Liechtenstein', '423'),
    Country('LT', 'Lithuania', '370'),
    Country('LU', 'Luxembourg', '352'),
    Country('MO', 'Macao', '853'),
    Country('MG', 'Madagascar', '261'),
    Country('MW', 'Malawi', '265'),
    Country('MY', 'Malaysia', '60'),
    Country('MV', 'Maldives', '960'),
    Country('ML', 'Mali', '223'),
    Country('MT', 'Malta', '356'),
    Country('MH', 'Marshall Islands', '692'),
    Country('MR', 'Mauritania', '222'),
    Country('MU', 'Mauritius', '230'),
    Country('MX', 'Mexico', '52'),
    Country('FM', 'Micronesia', '691'),
    Country('MD', 'Moldova', '373'),
    Country('MC', 'Monaco', '377'),
    Country('MN', 'Mongolia', '976'),
    Country('ME', 'Montenegro', '382'),
    Country('MA', 'Morocco', '212'),
    Country('MZ', 'Mozambique', '258'),
    Country('MM', 'Myanmar', '95'),
    Country('NA', 'Namibia', '264'),
    Country('NR', 'Nauru', '674'),
    Country('NP', 'Nepal', '977'),
    Country('NL', 'Netherlands', '31'),
    Country('NZ', 'New Zealand', '64'),
    Country('NI', 'Nicaragua', '505'),
    Country('NE', 'Niger', '227'),
    Country('NG', 'Nigeria', '234'),
    Country('KP', 'North Korea', '850'),
    Country('MK', 'North Macedonia', '389'),
    Country('NO', 'Norway', '47'),
    Country('OM', 'Oman', '968'),
    Country('PK', 'Pakistan', '92'),
    Country('PW', 'Palau', '680'),
    Country('PS', 'Palestine', '970'),
    Country('PA', 'Panama', '507'),
    Country('PG', 'Papua New Guinea', '675'),
    Country('PY', 'Paraguay', '595'),
    Country('PE', 'Peru', '51'),
    Country('PH', 'Philippines', '63'),
    Country('PL', 'Poland', '48'),
    Country('PT', 'Portugal', '351'),
    Country('PR', 'Puerto Rico', '1'),
    Country('QA', 'Qatar', '974'),
    Country('RO', 'Romania', '40'),
    Country('RU', 'Russia', '7'),
    Country('RW', 'Rwanda', '250'),
    Country('KN', 'Saint Kitts and Nevis', '1'),
    Country('LC', 'Saint Lucia', '1'),
    Country('VC', 'Saint Vincent and the Grenadines', '1'),
    Country('WS', 'Samoa', '685'),
    Country('SM', 'San Marino', '378'),
    Country('ST', 'São Tomé and Príncipe', '239'),
    Country('SA', 'Saudi Arabia', '966'),
    Country('SN', 'Senegal', '221'),
    Country('RS', 'Serbia', '381'),
    Country('SC', 'Seychelles', '248'),
    Country('SL', 'Sierra Leone', '232'),
    Country('SG', 'Singapore', '65'),
    Country('SK', 'Slovakia', '421'),
    Country('SI', 'Slovenia', '386'),
    Country('SB', 'Solomon Islands', '677'),
    Country('SO', 'Somalia', '252'),
    Country('ZA', 'South Africa', '27'),
    Country('KR', 'South Korea', '82'),
    Country('SS', 'South Sudan', '211'),
    Country('ES', 'Spain', '34'),
    Country('LK', 'Sri Lanka', '94'),
    Country('SD', 'Sudan', '249'),
    Country('SR', 'Suriname', '597'),
    Country('SE', 'Sweden', '46'),
    Country('CH', 'Switzerland', '41'),
    Country('SY', 'Syria', '963'),
    Country('TW', 'Taiwan', '886'),
    Country('TJ', 'Tajikistan', '992'),
    Country('TZ', 'Tanzania', '255'),
    Country('TH', 'Thailand', '66'),
    Country('TL', 'Timor-Leste', '670'),
    Country('TG', 'Togo', '228'),
    Country('TO', 'Tonga', '676'),
    Country('TT', 'Trinidad and Tobago', '1'),
    Country('TN', 'Tunisia', '216'),
    Country('TR', 'Türkiye', '90'),
    Country('TM', 'Turkmenistan', '993'),
    Country('TV', 'Tuvalu', '688'),
    Country('UG', 'Uganda', '256'),
    Country('UA', 'Ukraine', '380'),
    Country('AE', 'United Arab Emirates', '971'),
    Country('GB', 'United Kingdom', '44'),
    Country('US', 'United States', '1'),
    Country('UY', 'Uruguay', '598'),
    Country('UZ', 'Uzbekistan', '998'),
    Country('VU', 'Vanuatu', '678'),
    Country('VA', 'Vatican City', '39'),
    Country('VE', 'Venezuela', '58'),
    Country('VN', 'Vietnam', '84'),
    Country('YE', 'Yemen', '967'),
    Country('ZM', 'Zambia', '260'),
    Country('ZW', 'Zimbabwe', '263'),
  ];
}
